spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      initial-size: 3
      min-idle: 3
      max-active: 10
      stat-view-servlet:
        login-username: admin
        login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
mybatis:
  type-aliases-package: springboot2.model
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml

